name: CI-CMMI

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build-test-security:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install bandit pytest coverage

    # ► GOV – Seguridad (usa script)
    - name: GOV – Check compliance script
      run: bash scripts/gov_check_compliance.sh

    # ► PCM – Gate de proceso (exige CHANGELOG.md)
    - name: PCM – CHANGELOG gate
      run: python scripts/pcm_gate_pipeline.py

    # ► Pruebas + cobertura
    - name: Run tests and generate coverage
      run: |
        coverage run -m pytest
        coverage xml -o coverage.xml

    - name: Upload coverage artifact
      uses: actions/upload-artifact@v4
      with:
        name: coverage
        path: coverage.xml

    # ► MPM – Registrar KPI de cobertura
    - name: MPM – Registrar cobertura
      run: python scripts/mpm_kpi_tracker.py coverage.xml
